# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c8e9d89293948170ef1a2125e947cb798464b267bbeb9e81fd949a529925c7c5d336676f1c9e1b4a63042fa041c6f1dd925a935793b9c5b585f091165790417b

test:
  secret_key_base: c4495997002247a08adf14c8a9b0ce64ad95ee518920cb7add1b1b860fbb6e40283bc05e6578f554279f9178260775a7661414b7cfb0d2fbe48bd9654d49780f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
